name=ESP32_SharpIR
version=1.0.1
author=Ramdesh Gustiar
maintainer=Ramdesh Gustiar
sentence=Sharp IR GP2Y0A21YK0F library with regression models and filtering
paragraph=Arduino library for ESP32 that converts Sharp IR analog output into distance using power and inverse regression models combined with median filtering
category=Sensors
architectures=esp32
url=https://github.com/newbiei/ESP32_SharpIR
includes=WERA_SharpIR.h